name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - python -m pip install –upgrade pip
    - pip3 install -r requirements.txt
    - python3 server.py > log.txt 2>&1 &

