name: Check Website Element

on:
  schedule:
    - cron: '*/1 * * * *'
  push:

jobs:
  check-website:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Selenium and WebDriver Manager
        run: |
          pip install selenium webdriver-manager
      
      - name: Check Element on Website
        run: python check_element.py
